### ISSUE TITLE
The sentences in the dataset don't match each other

### ISSUE THREAD

**Issue by LauraMQuiros** [Voytech-0/NatLanPro#16]
data: when splitting through newlines we have a total of 5094 empty lines

- [x] splitting through new lines - problem: there are newlines in the middle of a spanish sentence, not in english one
- [x]  splitting through dots - problem: not all sentences finish in a dot, sometimes we have dots in the middle of a sentence, of a spanish translation uses multiple sentences and english uses 1 
- [x] splitting through both commas and dots - problem: different amounts of commas
- [x] deleting empty lines - problem: you still have uneven split

currently trying: if one of them is empty, attach translation is equivalent to, to the prev row

**Comment by Voytech-0** [comment]
It seems that there are some existing solutions to processing EuroParl corpora. I am not sure how useful that would be
https://github.com/mustaszewski/europarl-extract

**Comment by LauraMQuiros** [comment]
This actually solves it! will drop update with more clear overview of commands to run (we don't need all the explanations from the original repo) tmr morning

**Comment by LauraMQuiros** [comment]
nvm this still doesn't fully work
